version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10  # Adjust Python version if needed
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Starting build process..."
  build:
    commands:
      - echo "Running SageMaker update script..."
      - python update_sagemaker_model.py
artifacts:
  files:
    - '**/*'
