AWSTemplateFormatVersion: '2010-09-09'
Resources:
  StrokePredictionPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::691879165105:role/CCL-SageMaker-Role
      ArtifactStore:
        Type: S3
        Location: s3://2124323strokepred/ml-project/model/ci-cd/deploy/
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit # or GitHub
                Version: 1
              Configuration:
                RepositoryName: https://github.com/kkvasi/
                BranchName: main
              OutputArtifacts:
                - Name: SourceOutput
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: MLops_mc1.git
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: Lambda
                Version: 1
              Configuration:
                FunctionName: update-stroke-model-lambda
              InputArtifacts:
                - Name: BuildOutput
